### ISSUE TITLE
Importing modules into `commands.ts` prevents `Cypress.Chainable` declaration merging

### ISSUE THREAD

**Issue by shcallaway** [cypress-io/add-cypress-custom-command-in-typescript#2]
Importing modules into `commands.ts` prevents the `Cypress.Chainable` declaration merging for some reason. A user should be able to import additional modules into `commands.ts`.

Before:

![image](https://user-images.githubusercontent.com/7094076/34546035-148e7d50-f0a6-11e7-9309-12b1571fe00b.png)

After:

![image](https://user-images.githubusercontent.com/7094076/34546030-0be3ece4-f0a6-11e7-8a6e-60321d199d5a.png)

Note that the second `Cypress.Chainable` definition is no longer merged with the first.

To repro:

1. Create an empty `cypress/test-module.ts`:

```
export default {}
```

2. Add `import "../test-module"` to the top of `commands.ts`.

**Comment by bahmutov** [comment]
That's great! I mean great that there is the definite bug and simple steps to reproduce

**Comment by shcallaway** [comment]
A temporary workaround (and probably a clue to the bug) is, you can use `require` syntax — just not `import`.

**Comment by shcallaway** [comment]
I think this is related: TypeScript treats `commands.ts` as a module if it [contains any import or export statements](https://stackoverflow.com/a/41975448/6137628). If it doesn't, TypeScript treats it as a script. So when `commands.ts` is a module, the declaration merging doesn't occur?

**Comment by bahmutov** [comment]
That might be it, but sounds like a bug to me. I will have to search through typescript issues

**Comment by darina-techery** [comment]
What would you do if you needed to import type in commands.ts?
I prefer to have my custom commands typed, but the return value is a custom class declared in my project. When I use `import { MyCustomClass } from "./custom-class";` statement, it immediately breaks down the whole commands.ts stuff. And I can't require a type, interface or class, as they are not objects. 
I can fallback to using `any`, but this looks like last resort to me. Would you suggest any other options?

**Comment by fr-ser** [comment]
Is this bug actually closed?
I do want to import a typescript enum and my file still crashes with "TS2304: Cannot find name 'require'."

**Comment by crosscompile** [comment]
A workaround that has allowed me to add import and export statements to my `commands.ts` is to explicitly declare `Cypress` on the global namespace:
```ts
import { MyCustomClass } from './custom-class';

declare global {
  namespace Cypress {
    interface Chainable {
      customCommand: typeof customCommand;
    }
  }
}

function customCommand(input: MyCustomClass) {
  // ...
}

Cypress.Commands.add('customCommand', customCommand);
```

**Comment by Lukaszli** [comment]
Hi, so this issue has been resolved in some way? Do I need to use a workaround?
(And what is inside MyCustomClass in the workaround solution?) 

Cheers :)

**Comment by charlex** [comment]
I too am at least looking for a bit of guidance here. Perhaps there are project examples of this out there that folks go refer to? Or documentation on Cypress's site?

**Comment by devinrhode2** [comment]
For any TS newbies: if you're getting a red squiggly on `declare global` - maybe you forgot to rename .js file to .ts :)

**Comment by michael-mckenna** [comment]
@devinrhode2 That didn't work for me either :/ had to add `export {}` at the top for it to finally work.

**Comment by kaspatel-mdsol** [comment]
> A workaround that has allowed me to add import and export statements to my `commands.ts` is to explicitly declare `Cypress` on the global namespace:
> 
> ```ts
> import { MyCustomClass } from './custom-class';
> 
> declare global {
>   namespace Cypress {
>     interface Chainable {
>       customCommand: typeof customCommand;
>     }
>   }
> }
> 
> function customCommand(input: MyCustomClass) {
>   // ...
> }
> 
> Cypress.Commands.add('customCommand', customCommand);
> ```

This works. But typescript support for cypress can most certainly be improved. One doesn't have to waste so much time figuring out such a simple use-case.

**Comment by bahmutov** [comment]
Absolutely agree, and we are open to any pull requests improving it.

**Comment by nemanjamilosavljevic-newtron** [comment]
> @devinrhode2 That didn't work for me either :/ had to add `export {}` at the top for it to finally work.

Could you please provide an example of how you've made it work?
This is what I have at the moment:
```ts
/// <reference types="cypress" />

import {loginThing} from "./commands";

export {};

declare global {
  namespace Cypress {
    interface Chainable<Subject> {
      /**
       * Custom command to perform the login by filling in the email and password and submitting them
       * @param email
       * @param password
       * @example
       * cy.loginThing('email@domain.com', 'password-value');
       */
      loginThing: typeof loginThing;
    }
  }
}
```

**Comment by LuisTovar0** [comment]
> A temporary workaround (and probably a clue to the bug) is, you can use `require` syntax — just not `import`.

This works, but every import comes with type any

> A workaround that has allowed me to add import and export statements to my `commands.ts` is to explicitly declare `Cypress` on the global namespace:
> 
> ```ts
> import { MyCustomClass } from './custom-class';
> 
> declare global {
>   namespace Cypress {
>     interface Chainable {
>       customCommand: typeof customCommand;
>     }
>   }
> }
> 
> function customCommand(input: MyCustomClass) {
>   // ...
> }
> 
> Cypress.Commands.add('customCommand', customCommand);
> ```

This gives me the `TS2669: Augumentations for the global scope can only be directly nested in external modules or ambient module declarations` compiler error on the `global` keyword. What am I missing? (I'm testing an Angular app)
